#!/usr/bin/env python3
"""Generate compact 1-bit DejaVu glyph tables for the e-paper UI."""

from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "components" / "epaper" / "epaper_fonts.c"

SANS = Path("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf")
MONO = Path("/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf")

FONT_SPECS = (
    ("hero_sans_54", SANS, 54, "%0123456789"),
    ("mono_16", MONO, 16, "".join(chr(value) for value in range(32, 91))),
    ("mono_13", MONO, 13, "".join(chr(value) for value in range(32, 91))),
    ("mono_10", MONO, 10, "".join(chr(value) for value in range(32, 91))),
)


def packed_bitmap(image: Image.Image) -> list[int]:
    bits = [1 if pixel >= 128 else 0 for pixel in image.getdata()]
    packed = []

    for index in range(0, len(bits), 8):
        value = 0
        for offset, bit in enumerate(bits[index:index + 8]):
            value |= bit << (7 - offset)
        packed.append(value)

    return packed


def render_font(name: str, path: Path, size: int, characters: str) -> dict:
    font = ImageFont.truetype(str(path), size)
    first = min(ord(character) for character in characters)
    last = max(ord(character) for character in characters)
    boxes = [font.getbbox(character, anchor="ls") for character in characters]
    font_top = min(box[1] for box in boxes)
    font_bottom = max(box[3] for box in boxes)
    bitmaps: list[int] = []
    glyphs = []

    for codepoint in range(first, last + 1):
        character = chr(codepoint)
        if character not in characters:
            glyphs.append((len(bitmaps), 0, 0, 0, 0, 0))
            continue

        left, top, right, bottom = font.getbbox(character, anchor="ls")
        width = max(0, right - left)
        height = max(0, bottom - top)
        advance = round(font.getlength(character))
        offset = len(bitmaps)

        if width > 0 and height > 0:
            image = Image.new("L", (width, height), 0)
            draw = ImageDraw.Draw(image)
            draw.text(
                (-left, -top),
                character,
                font=font,
                fill=255,
                anchor="ls",
            )
            bitmaps.extend(packed_bitmap(image))

        glyphs.append(
            (
                offset,
                width,
                height,
                left,
                top - font_top,
                advance,
            )
        )

    return {
        "name": name,
        "first": first,
        "last": last,
        "line_height": font_bottom - font_top,
        "bitmaps": bitmaps,
        "glyphs": glyphs,
    }


def byte_lines(values: list[int]) -> str:
    if not values:
        return "    0x00,"

    rows = []
    for index in range(0, len(values), 12):
        row = ", ".join(f"0x{value:02X}" for value in values[index:index + 12])
        rows.append(f"    {row},")
    return "\n".join(rows)


def generate() -> None:
    fonts = [render_font(*spec) for spec in FONT_SPECS]
    lines = [
        "/*",
        " * Generated by tools/generate_epaper_fonts.py from DejaVu Sans and",
        " * DejaVu Sans Mono. See FONTS_LICENSE.txt for the font license.",
        " */",
        '#include "epaper_fonts.h"',
        "",
    ]

    for font in fonts:
        name = font["name"]
        lines.extend(
            [
                f"static const uint8_t {name}_bitmap[] = {{",
                byte_lines(font["bitmaps"]),
                "};",
                "",
                f"static const epaper_glyph_t {name}_glyphs[] = {{",
            ]
        )

        for offset, width, height, x_offset, y_offset, advance in font["glyphs"]:
            lines.append(
                "    {"
                f"{offset}, {width}, {height}, {x_offset}, {y_offset}, {advance}"
                "},"
            )

        public_name = f"EPAPER_FONT_{name.upper()}"
        lines.extend(
            [
                "};",
                "",
                f"const epaper_font_t {public_name} = {{",
                f"    .bitmap = {name}_bitmap,",
                f"    .glyphs = {name}_glyphs,",
                f"    .first = {font['first']},",
                f"    .last = {font['last']},",
                f"    .line_height = {font['line_height']},",
                "};",
                "",
            ]
        )

    OUTPUT.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    generate()
